# Generated by Django 3.0.6 on 2020-05-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_job_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='summary',
            field=models.CharField(default='sdfdsfsdfs', max_length=200),
            preserve_default=False,
        ),
    ]
